// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using graphql_library_management.Models;

#nullable disable

namespace graphql_library_management.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20240130110808_AddSeedValueAuthorPerson")]
    partial class AddSeedValueAuthorPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("graphql_library_management.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Biography of John Doe",
                            BirthDate = new DateTime(1982, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Biography of Jane Smith",
                            BirthDate = new DateTime(1970, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bob Brown"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Biography of Bob Brown",
                            BirthDate = new DateTime(1986, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Biography of Bob Brown",
                            BirthDate = new DateTime(1986, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Biography of Jane Smith",
                            BirthDate = new DateTime(1975, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eve Wilson"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Biography of Bob Brown",
                            BirthDate = new DateTime(1983, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eve Wilson"
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Biography of Eve Wilson",
                            BirthDate = new DateTime(1983, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Biography of Alice Johnson",
                            BirthDate = new DateTime(1978, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 9,
                            Biography = "Biography of John Doe",
                            BirthDate = new DateTime(1984, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 10,
                            Biography = "Biography of Eve Wilson",
                            BirthDate = new DateTime(1991, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 11,
                            Biography = "Biography of John Doe",
                            BirthDate = new DateTime(1975, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 12,
                            Biography = "Biography of Bob Brown",
                            BirthDate = new DateTime(1977, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 13,
                            Biography = "Biography of Bob Brown",
                            BirthDate = new DateTime(1976, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bob Brown"
                        },
                        new
                        {
                            Id = 14,
                            Biography = "Biography of Eve Wilson",
                            BirthDate = new DateTime(1988, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 15,
                            Biography = "Biography of Eve Wilson",
                            BirthDate = new DateTime(1979, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 16,
                            Biography = "Biography of John Doe",
                            BirthDate = new DateTime(1971, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eve Wilson"
                        },
                        new
                        {
                            Id = 17,
                            Biography = "Biography of Jane Smith",
                            BirthDate = new DateTime(1973, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 18,
                            Biography = "Biography of Jane Smith",
                            BirthDate = new DateTime(1985, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 19,
                            Biography = "Biography of Alice Johnson",
                            BirthDate = new DateTime(1983, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bob Brown"
                        },
                        new
                        {
                            Id = 20,
                            Biography = "Biography of Alice Johnson",
                            BirthDate = new DateTime(1995, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bob Brown"
                        });
                });

            modelBuilder.Entity("graphql_library_management.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("graphql_library_management.Models.Book", b =>
                {
                    b.HasOne("graphql_library_management.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("graphql_library_management.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
