// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using graphql_library_management.Models;

#nullable disable

namespace graphql_library_management.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20240130111227_AddSeedValueBook")]
    partial class AddSeedValueBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("graphql_library_management.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Biography of Jane Smith",
                            BirthDate = new DateTime(1992, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Biography of John Doe",
                            BirthDate = new DateTime(1989, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Biography of John Doe",
                            BirthDate = new DateTime(1982, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eve Wilson"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Biography of Jane Smith",
                            BirthDate = new DateTime(1993, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Biography of Bob Brown",
                            BirthDate = new DateTime(1973, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Biography of Alice Johnson",
                            BirthDate = new DateTime(1995, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Biography of John Doe",
                            BirthDate = new DateTime(1977, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Biography of Jane Smith",
                            BirthDate = new DateTime(1987, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 9,
                            Biography = "Biography of Eve Wilson",
                            BirthDate = new DateTime(1992, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 10,
                            Biography = "Biography of Eve Wilson",
                            BirthDate = new DateTime(1986, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 11,
                            Biography = "Biography of John Doe",
                            BirthDate = new DateTime(1976, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bob Brown"
                        },
                        new
                        {
                            Id = 12,
                            Biography = "Biography of Eve Wilson",
                            BirthDate = new DateTime(1998, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 13,
                            Biography = "Biography of Bob Brown",
                            BirthDate = new DateTime(1986, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eve Wilson"
                        },
                        new
                        {
                            Id = 14,
                            Biography = "Biography of Eve Wilson",
                            BirthDate = new DateTime(1975, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eve Wilson"
                        },
                        new
                        {
                            Id = 15,
                            Biography = "Biography of Eve Wilson",
                            BirthDate = new DateTime(1992, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 16,
                            Biography = "Biography of Bob Brown",
                            BirthDate = new DateTime(1999, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 17,
                            Biography = "Biography of Alice Johnson",
                            BirthDate = new DateTime(1990, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 18,
                            Biography = "Biography of Bob Brown",
                            BirthDate = new DateTime(1985, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 19,
                            Biography = "Biography of John Doe",
                            BirthDate = new DateTime(1976, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 20,
                            Biography = "Biography of Alice Johnson",
                            BirthDate = new DateTime(1990, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eve Wilson"
                        });
                });

            modelBuilder.Entity("graphql_library_management.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 17,
                            CoverImageUrl = "https://example.com/book-covers/book1.jpg",
                            Description = "Description B",
                            Genre = "Fiction",
                            PublishedDate = new DateTime(2022, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            Synopsis = "Synopsis D",
                            Title = "Book D"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 6,
                            CoverImageUrl = "https://example.com/book-covers/book2.jpg",
                            Description = "Description D",
                            Genre = "Mystery",
                            PublishedDate = new DateTime(2006, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 1,
                            Synopsis = "Synopsis A",
                            Title = "Book D"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 10,
                            CoverImageUrl = "https://example.com/book-covers/book3.jpg",
                            Description = "Description A",
                            Genre = "Science Fiction",
                            PublishedDate = new DateTime(2020, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            Synopsis = "Synopsis C",
                            Title = "Book D"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 2,
                            CoverImageUrl = "https://example.com/book-covers/book4.jpg",
                            Description = "Description C",
                            Genre = "Romance",
                            PublishedDate = new DateTime(2006, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            Synopsis = "Synopsis A",
                            Title = "Book C"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 18,
                            CoverImageUrl = "https://example.com/book-covers/book5.jpg",
                            Description = "Description C",
                            Genre = "Fiction",
                            PublishedDate = new DateTime(2010, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            Synopsis = "Synopsis E",
                            Title = "Book D"
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 17,
                            CoverImageUrl = "https://example.com/book-covers/book6.jpg",
                            Description = "Description E",
                            Genre = "Mystery",
                            PublishedDate = new DateTime(2002, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            Synopsis = "Synopsis D",
                            Title = "Book D"
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 9,
                            CoverImageUrl = "https://example.com/book-covers/book7.jpg",
                            Description = "Description B",
                            Genre = "Science Fiction",
                            PublishedDate = new DateTime(2015, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            Synopsis = "Synopsis B",
                            Title = "Book E"
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 5,
                            CoverImageUrl = "https://example.com/book-covers/book8.jpg",
                            Description = "Description E",
                            Genre = "Science Fiction",
                            PublishedDate = new DateTime(2000, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            Synopsis = "Synopsis D",
                            Title = "Book A"
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 13,
                            CoverImageUrl = "https://example.com/book-covers/book9.jpg",
                            Description = "Description B",
                            Genre = "Romance",
                            PublishedDate = new DateTime(2017, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            Synopsis = "Synopsis B",
                            Title = "Book A"
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 14,
                            CoverImageUrl = "https://example.com/book-covers/book10.jpg",
                            Description = "Description D",
                            Genre = "Science Fiction",
                            PublishedDate = new DateTime(2014, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            Synopsis = "Synopsis A",
                            Title = "Book E"
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 20,
                            CoverImageUrl = "https://example.com/book-covers/book11.jpg",
                            Description = "Description A",
                            Genre = "Fantasy",
                            PublishedDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 1,
                            Synopsis = "Synopsis A",
                            Title = "Book B"
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 20,
                            CoverImageUrl = "https://example.com/book-covers/book12.jpg",
                            Description = "Description E",
                            Genre = "Mystery",
                            PublishedDate = new DateTime(2002, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            Synopsis = "Synopsis E",
                            Title = "Book D"
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 13,
                            CoverImageUrl = "https://example.com/book-covers/book13.jpg",
                            Description = "Description D",
                            Genre = "Science Fiction",
                            PublishedDate = new DateTime(2020, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            Synopsis = "Synopsis B",
                            Title = "Book B"
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 5,
                            CoverImageUrl = "https://example.com/book-covers/book14.jpg",
                            Description = "Description D",
                            Genre = "Mystery",
                            PublishedDate = new DateTime(2016, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            Synopsis = "Synopsis E",
                            Title = "Book A"
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 2,
                            CoverImageUrl = "https://example.com/book-covers/book15.jpg",
                            Description = "Description D",
                            Genre = "Mystery",
                            PublishedDate = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            Synopsis = "Synopsis C",
                            Title = "Book E"
                        },
                        new
                        {
                            BookId = 16,
                            AuthorId = 17,
                            CoverImageUrl = "https://example.com/book-covers/book16.jpg",
                            Description = "Description B",
                            Genre = "Fantasy",
                            PublishedDate = new DateTime(2006, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 1,
                            Synopsis = "Synopsis E",
                            Title = "Book C"
                        },
                        new
                        {
                            BookId = 17,
                            AuthorId = 9,
                            CoverImageUrl = "https://example.com/book-covers/book17.jpg",
                            Description = "Description A",
                            Genre = "Science Fiction",
                            PublishedDate = new DateTime(2013, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            Synopsis = "Synopsis C",
                            Title = "Book E"
                        },
                        new
                        {
                            BookId = 18,
                            AuthorId = 12,
                            CoverImageUrl = "https://example.com/book-covers/book18.jpg",
                            Description = "Description D",
                            Genre = "Romance",
                            PublishedDate = new DateTime(2001, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            Synopsis = "Synopsis E",
                            Title = "Book C"
                        },
                        new
                        {
                            BookId = 19,
                            AuthorId = 6,
                            CoverImageUrl = "https://example.com/book-covers/book19.jpg",
                            Description = "Description E",
                            Genre = "Romance",
                            PublishedDate = new DateTime(2003, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            Synopsis = "Synopsis C",
                            Title = "Book D"
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 16,
                            CoverImageUrl = "https://example.com/book-covers/book20.jpg",
                            Description = "Description C",
                            Genre = "Science Fiction",
                            PublishedDate = new DateTime(2002, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            Synopsis = "Synopsis B",
                            Title = "Book B"
                        });
                });

            modelBuilder.Entity("graphql_library_management.Models.Book", b =>
                {
                    b.HasOne("graphql_library_management.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("graphql_library_management.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
